source "https://rubygems.org"

gemspec

gem "rails", ">= 8.0"

gem "puma"

gem "sqlite3"

gem "propshaft"

# Omakase Ruby styling [https://github.com/rails/rubocop-rails-omakase/]
gem "rubocop-rails-omakase", require: false

# Start debugger with binding.b [https://github.com/ruby/debug]
# gem "debug", ">= 1.0.0"

gem "lexoffice_client", path: "../lexoffice_client"

group :development, :test do
  gem "bootsnap"
  gem "factory_bot"
  gem "guard-bundler"
  gem "guard-rspec"
  gem "guard-standardrb"
  gem "rspec-rails"
  gem "standardrb"
  gem "vcr"
  gem "webmock"
end