source "https://rubygems.org"

gemspec

group :development, :test do
  gem "factory_bot"
  gem "guard-bundler"
  gem "guard-rspec"
  gem "guard-standardrb"
  gem "rspec"
  gem "standardrb"
  gem "vcr"
  gem "webmock"
end